### PR TITLE
completed

### PR DESCRIPTION
**Pull request by mikidoodle**
I’ve added support till decillions. This is to help with your package.
Definitely not for a t-shirt and stickers.

ok it is.
Have a nice day!

### CODE REVIEW

**Comment by cremble-cloud** [comment]
Oh thank you!
Let me just check if the code works, and you can _maybe_ get 1/4th of a t shirt!

**Comment by mikidoodle** [comment]
👍

**Comment by cremble-cloud** [comment]
Works fine! Thank you!

**Comment by mikidoodle** [comment]
Thank you so much!

**Pull request merged**
